# Hugo
title = "My Docs"
description = "Congrats on setting up a new Doks project!"
images = ["cover.png"]

# mainSections
mainSections = ["docs"]

# Enable mathematical rendering on every page (unless you set the `math` parameter to `false` in front matter)
math = false
mathEngine = "KaTeX"

[social]
  twitter = "getdoks"

# Doks (@thulite/doks-core)
[doks]
  # Color mode
  colorMode = "auto"
  colorModeToggler = true

  # Navbar
  navbarSticky = true
  containerBreakpoint = "fluid"

  ## Button
  navBarButton = false
  navBarButtonUrl = "/docs/prologue/introduction/"
  navBarButtonText = "Get started"

  # FlexSearch
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  ## Search results
  showDate = false
  showSummary = true
  searchLimit = 99

  # Global alert
  alert = false
  alertDismissable = true

  # Bootstrap
  bootstrapJavascript = false

  # Nav
  sectionSwitcher = false
  sectionNav = ["docs", "writing", "portfolio"]
  toTopButton = false
  breadcrumbTrail = false
  headlineHash = true
  scrollSpy = true

  # Multilingual
  multilingualMode = false
  showMissingLanguages = true

  # Versioning
  docsVersioning = false
  docsVersion = "1.0"

  # UX
  headerBar = false
  backgroundDots = true
  aiButtons = true

  # Homepage
  sectionFooter = false

  # Blog
  relatedPosts = false
  imageList = true
  imageSingle = true

  # Repository
  editPage = false
  lastMod = false
  repoHost = "GitHub"
  docsRepo = "https://github.com/h-enk/doks"
  docsRepoBranch = "main"
  docsRepoSubPath = ""

# Debug
[render_hooks.image]
  errorLevel = 'ignore'

[render_hooks.link]
  errorLevel = 'ignore'
  highlightBroken = false

[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 576, 768, 1025, 1200, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

[inline_svg]
  iconSetDir = "tabler-icons"
  iconSetVariant = "outline"

[seo]
  [seo.description]
    summaryFallback = ""

  [seo.title]
    separator = " | "
    suffix = ""

  [seo.favicons]
    sizes = []
    icon = "favicon.png"
    svgIcon = "favicon.svg"
    maskIcon = "mask-icon.svg"
    maskIconColor = "white"

  [seo.schemas]
    type = "Organization"
    logo = "favicon-512x512.png"
    name = "Thulite"
    sameAs = []
    images = ["cover.png"]
    article = []
    newsArticle = []
    blogPosting = ["blog"]
    product = []
